[project]
name = "drs4"
version = "0.6.0"
description = "Control and data acquisition software for FINER/DRS4"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "dateparser>=1",
    "matplotlib>=3",
    "numpy>=2",
    "pillow>=10",
    "pyserial>=3",
    "tqdm>=4",
    "typing-extensions>=4",
    "xarray[parallel]>=2025",
    "xarrayspecs>=0.10,<1.0",
    "zarr>=3",
]
keywords = [
    "astronomy",
    "drs4",
    "finer",
    "lmt",
    "millimeter",
    "python",
    "radio-astronomy",
    "single-dish",
    "submillimeter",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[[project.authors]]
name = "Akio Taniguchi"
email = "mail@taniguchiak.io"

[project.license]
file = "LICENSE"

[project.urls]
homepage = "https://finerreceiver.github.io/drs4"
repository = "https://github.com/finerreceiver/drs4"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=25,<27",
    "ipython>=8,<10",
    "myst-parser>=4,<6",
    "pandas-stubs>=2",
    "pydata-sphinx-theme>=0.18,<1.0",
    "pyright>=1,<2",
    "pytest>=9,<10",
    "sphinx>=8,<10",
]

[tool.pyright]
typeCheckingMode = "basic"
reportIncompatibleMethodOverride = "warning"
reportUnknownMemberType = "warning"
